import type { BattleRegion, Monster } from '../types/game';

export const NORMAL_MONSTERS_DATA: Monster[] = [
  { id: 'skeleton', name: '骷髅战士', icon: '💀', tier: 'normal', maxHp: 130, attack: 16, defense: 7, threatTypes: ['tank_breaker'] },
  { id: 'zombie', name: '腐烂僵尸', icon: '🧟', tier: 'normal', maxHp: 152, attack: 14, defense: 10, threatTypes: ['attrition'] },
  { id: 'goblin', name: '地穴哥布林', icon: '👺', tier: 'normal', maxHp: 118, attack: 19, defense: 6, threatTypes: ['sustain_pressure'] },
  { id: 'wraith', name: '幽影亡灵', icon: '👻', tier: 'normal', maxHp: 140, attack: 17, defense: 8, threatTypes: ['attrition'] },
  { id: 'slime', name: '史莱姆', icon: '🟢', tier: 'normal', maxHp: 104, attack: 12, defense: 4, threatTypes: ['tank_breaker'] },
  { id: 'bandit', name: '盗贼', icon: '🦹', tier: 'normal', maxHp: 124, attack: 20, defense: 7, threatTypes: ['sustain_pressure'] },
  { id: 'cultist', name: '邪教徒', icon: '🔮', tier: 'normal', maxHp: 136, attack: 15, defense: 8, threatTypes: ['attrition'] },
  { id: 'giant_rat', name: '巨型老鼠', icon: '🐀', tier: 'normal', maxHp: 92, attack: 13, defense: 3, threatTypes: ['tank_breaker'] },
  { id: 'stone_golem', name: '岩甲魔像', icon: '🗿', tier: 'normal', maxHp: 188, attack: 16, defense: 17, threatTypes: ['burst_punish', 'tank_breaker'] },
  { id: 'lava_hound', name: '熔火猎犬', icon: '🐺', tier: 'normal', maxHp: 150, attack: 23, defense: 7, threatTypes: ['sustain_pressure'] },
  { id: 'poison_spider', name: '毒牙蛛后', icon: '🕷️', tier: 'normal', maxHp: 118, attack: 22, defense: 5, traits: ['double_attack'], threatTypes: ['sustain_pressure'] },
  { id: 'frost_mage', name: '寒霜法徒', icon: '🧊', tier: 'normal', maxHp: 126, attack: 23, defense: 4, threatTypes: ['sustain_pressure'] },
  { id: 'harpy', name: '裂空鹰妖', icon: '🦅', tier: 'normal', maxHp: 130, attack: 19, defense: 7, threatTypes: ['tank_breaker'] },
  { id: 'mimic', name: '噬财宝箱怪', icon: '📦', tier: 'normal', maxHp: 164, attack: 17, defense: 11, threatTypes: ['burst_punish'] },
  { id: 'void_eye', name: '虚空之眼', icon: '👁️', tier: 'normal', maxHp: 142, attack: 19, defense: 8, threatTypes: ['attrition'] },
  { id: 'forest_satyr', name: '荒林萨堤', icon: '🌿', tier: 'normal', maxHp: 124, attack: 17, defense: 7, threatTypes: ['tank_breaker'] },
  { id: 'shadow_assassin', name: '暗影刺客', icon: '🗡️', tier: 'normal', maxHp: 120, attack: 25, defense: 5, threatTypes: ['sustain_pressure'] },
  { id: 'bone_shaman', name: '白骨祭司', icon: '🦴', tier: 'normal', maxHp: 140, attack: 20, defense: 8, threatTypes: ['attrition'] },
  { id: 'iron_knight', name: '铁誓骑士', icon: '🛡️', tier: 'normal', maxHp: 196, attack: 18, defense: 19, traits: ['shield_on_start'], threatTypes: ['burst_punish', 'tank_breaker'] },
  { id: 'plague_doctor', name: '疫病医师', icon: '🕯️', tier: 'normal', maxHp: 132, attack: 22, defense: 7, threatTypes: ['attrition'] },
  { id: 'storm_elemental', name: '风暴元素', icon: '🌪️', tier: 'normal', maxHp: 154, attack: 26, defense: 5, traits: ['double_attack'], threatTypes: ['sustain_pressure'] },
  { id: 'blood_bat', name: '嗜血蝠王', icon: '🦇', tier: 'normal', maxHp: 112, attack: 23, defense: 4, traits: ['lifesteal'], threatTypes: ['attrition', 'sustain_pressure'] },
  { id: 'sand_wraith', name: '流沙怨灵', icon: '🏜️', tier: 'normal', maxHp: 146, attack: 21, defense: 10, threatTypes: ['attrition'] },
  { id: 'abyss_guard', name: '深渊守卫', icon: '⚔️', tier: 'normal', maxHp: 208, attack: 23, defense: 15, threatTypes: ['tank_breaker'] },
  { id: 'thorn_beast', name: '荆棘兽', icon: '🌵', tier: 'normal', maxHp: 176, attack: 19, defense: 12, traits: ['thorns'], threatTypes: ['burst_punish', 'attrition'] },
  { id: 'arcane_construct', name: '奥术构装体', icon: '🔷', tier: 'normal', maxHp: 170, attack: 24, defense: 11, threatTypes: ['tank_breaker'] },
  { id: 'grave_keeper', name: '守墓人', icon: '⚰️', tier: 'normal', maxHp: 156, attack: 21, defense: 10, threatTypes: ['attrition'] },
  { id: 'ashen_warlock', name: '灰烬术士', icon: '🔥', tier: 'normal', maxHp: 130, attack: 27, defense: 5, threatTypes: ['sustain_pressure'] },
  { id: 'crystal_lurker', name: '晶壳潜伏者', icon: '💎', tier: 'normal', maxHp: 182, attack: 20, defense: 13, threatTypes: ['burst_punish'] },
  { id: 'moon_huntress', name: '逐月女猎', icon: '🌙', tier: 'normal', maxHp: 126, attack: 25, defense: 7, threatTypes: ['sustain_pressure'] },
  { id: 'rot_brute', name: '腐败巨徒', icon: '🪓', tier: 'normal', maxHp: 220, attack: 28, defense: 8, threatTypes: ['tank_breaker', 'sustain_pressure'] },
];

export const BOSS_MONSTERS_DATA: Monster[] = [
  {
    id: 'abyss_demon',
    name: '深渊恶魔',
    icon: '👹',
    tier: 'boss',
    isBoss: true,
    maxHp: 430,
    attack: 39,
    defense: 20,
    traits: ['rage_on_low_hp'],
    uniqueTraits: ['rage_on_low_hp'],
    phases: [{ id: 'abyss-annihilation', label: '深渊湮灭', interval: 3, action: 'annihilation' }],
    threatTypes: ['sustain_pressure', 'attrition'],
    counterGoal: { title: '压制反击', stat: '防御力', threshold: 110, successText: '正面站桩可控', failText: '恶魔狂怒伤害暴走' },
  },
  {
    id: 'ancient_dragon',
    name: '远古巨龙',
    icon: '🐉',
    tier: 'boss',
    isBoss: true,
    maxHp: 500,
    attack: 44,
    defense: 23,
    traits: ['double_attack'],
    uniqueTraits: ['double_attack'],
    phases: [{ id: 'dragon-annihilation', label: '龙炎天罚', interval: 3, action: 'annihilation' }],
    threatTypes: ['sustain_pressure', 'tank_breaker'],
    counterGoal: { title: '高速斩首', stat: '攻击速度', threshold: 40, successText: '可抢先压制龙息', failText: '龙息节奏压死你' },
  },
  {
    id: 'dark_knight',
    name: '黑暗骑士',
    icon: '🛡️',
    tier: 'boss',
    isBoss: true,
    maxHp: 470,
    attack: 37,
    defense: 26,
    traits: ['shield_on_start'],
    uniqueTraits: ['shield_on_start'],
    phases: [{ id: 'knight-reconstruct', label: '黯铁重构', interval: 3, action: 'reconstruct' }],
    threatTypes: ['burst_punish', 'tank_breaker'],
    counterGoal: { title: '破甲门槛', stat: '攻击力', threshold: 300, successText: '可快速穿盾', failText: '被护盾拖入消耗战' },
  },
  {
    id: 'necromancer',
    name: '死灵法师',
    icon: '🧙',
    tier: 'boss',
    isBoss: true,
    maxHp: 390,
    attack: 35,
    defense: 17,
    traits: ['lifesteal'],
    uniqueTraits: ['lifesteal'],
    phases: [{ id: 'necro-drain', label: '亡魂汲取', interval: 3, action: 'drain_soul' }],
    threatTypes: ['attrition', 'sustain_pressure'],
    counterGoal: { title: '续航压制', stat: '吸血', threshold: 16, successText: '可跟上吸血拉扯', failText: '会被持续抽干' },
  },
  {
    id: 'storm_titan',
    name: '风暴泰坦',
    icon: '⚡',
    tier: 'boss',
    isBoss: true,
    maxHp: 530,
    attack: 48,
    defense: 22,
    traits: ['double_attack', 'rage_on_low_hp'],
    uniqueTraits: ['double_attack', 'rage_on_low_hp'],
    phases: [{ id: 'storm-annihilation', label: '雷霆湮灭', interval: 2, action: 'annihilation' }],
    threatTypes: ['sustain_pressure', 'tank_breaker'],
    counterGoal: { title: '元素抗压', stat: '元素伤害', threshold: 90, successText: '可在狂暴前斩杀', failText: '泰坦会进入连击收割' },
  },
  {
    id: 'scarlet_queen',
    name: '猩红女王',
    icon: '🩸',
    tier: 'boss',
    isBoss: true,
    maxHp: 480,
    attack: 41,
    defense: 24,
    traits: ['lifesteal', 'double_attack'],
    uniqueTraits: ['lifesteal', 'double_attack'],
    phases: [{ id: 'queen-drain', label: '猩红汲魂', interval: 3, action: 'drain_soul' }],
    threatTypes: ['attrition', 'sustain_pressure'],
    counterGoal: { title: '强韧血池', stat: '生命值', threshold: 2200, successText: '可撑过女王爆发窗', failText: '被连击与吸血碾压' },
  },
  {
    id: 'void_reaper',
    name: '虚空收割者',
    icon: '☠️',
    tier: 'boss',
    isBoss: true,
    maxHp: 510,
    attack: 45,
    defense: 23,
    traits: ['thorns'],
    uniqueTraits: ['thorns'],
    phases: [{ id: 'void-annihilation', label: '虚空湮灭', interval: 3, action: 'annihilation' }],
    threatTypes: ['burst_punish', 'attrition'],
    counterGoal: { title: '反伤互搏', stat: '反伤', threshold: 14, successText: '可反压收割节奏', failText: '输出会被反伤反噬' },
  },
  {
    id: 'clockwork_core',
    name: '失控核心',
    icon: '⚙️',
    tier: 'boss',
    isBoss: true,
    maxHp: 470,
    attack: 38,
    defense: 28,
    traits: ['shield_on_start', 'thorns'],
    uniqueTraits: ['shield_on_start', 'thorns'],
    phases: [{ id: 'core-reconstruct', label: '齿轮重构', interval: 3, action: 'reconstruct' }],
    threatTypes: ['burst_punish', 'tank_breaker'],
    counterGoal: { title: '爆发击穿', stat: '攻击力', threshold: 340, successText: '可压制重构循环', failText: '核心将无限叠盾' },
  },
];

export const REGION_MONSTER_IDS: Record<BattleRegion, string[]> = {
  forest: ['giant_rat', 'harpy', 'forest_satyr', 'blood_bat', 'poison_spider', 'moon_huntress', 'thorn_beast'],
  dungeon: ['skeleton', 'zombie', 'stone_golem', 'iron_knight', 'grave_keeper', 'mimic', 'abyss_guard'],
  volcano: ['lava_hound', 'ashen_warlock', 'storm_elemental', 'rot_brute', 'arcane_construct', 'frost_mage', 'void_eye'],
};
