import type { MapChapter, MapNode } from '../types/map';

export const MAP_CHAPTERS: MapChapter[] = [
  {
    id: 'chapter_forest',
    order: 1,
    name: '新手林地',
    description: '从基础战斗开始，学习装备与自动售卖。',
    nodeIds: ['n1', 'n2', 'n3'],
  },
  {
    id: 'chapter_dungeon',
    order: 2,
    name: '废弃地牢',
    description: '引入护盾与持续伤害压力。',
    nodeIds: ['n4', 'n5', 'n6'],
  },
  {
    id: 'chapter_volcano',
    order: 3,
    name: '熔岩深渊',
    description: '高压词缀与终章首领。',
    nodeIds: ['n7', 'n8', 'n9'],
  },
];

export const MAP_NODES: MapNode[] = [
  {
    id: 'n1',
    chapterId: 'chapter_forest',
    order: 1,
    name: '林地初战',
    description: '基础教学战，熟悉节奏。',
    encounterType: 'normal',
    region: 'forest',
    risk: 'safe',
    spawnMultiplier: 1,
    recommendedLevel: 1,
    firstClearRewardGold: 120,
    nextNodeIds: ['n2'],
  },
  {
    id: 'n2',
    chapterId: 'chapter_forest',
    order: 2,
    name: '补给小径',
    description: '学习背包管理与自动售卖。',
    encounterType: 'wave',
    region: 'forest',
    risk: 'safe',
    spawnMultiplier: 2,
    waveSize: 4,
    recommendedLevel: 2,
    firstClearRewardGold: 160,
    nextNodeIds: ['n3'],
  },
  {
    id: 'n3',
    chapterId: 'chapter_forest',
    order: 3,
    name: '林地守关者',
    description: '首个章节首领。',
    encounterType: 'boss',
    region: 'forest',
    risk: 'normal',
    spawnMultiplier: 1,
    recommendedLevel: 3,
    firstClearRewardGold: 280,
    nextNodeIds: ['n4'],
  },
  {
    id: 'n4',
    chapterId: 'chapter_dungeon',
    order: 4,
    name: '潮湿甬道',
    description: '护盾与高防敌人出现。',
    encounterType: 'normal',
    region: 'dungeon',
    risk: 'normal',
    spawnMultiplier: 1,
    recommendedLevel: 4,
    firstClearRewardGold: 220,
    nextNodeIds: ['n5'],
  },
  {
    id: 'n5',
    chapterId: 'chapter_dungeon',
    order: 5,
    name: '瘟疫囚室',
    description: '持续掉血压力测试。',
    encounterType: 'wave',
    region: 'dungeon',
    risk: 'normal',
    spawnMultiplier: 2,
    waveSize: 5,
    recommendedLevel: 5,
    firstClearRewardGold: 260,
    nextNodeIds: ['n6'],
  },
  {
    id: 'n6',
    chapterId: 'chapter_dungeon',
    order: 6,
    name: '深牢领主',
    description: '地牢章节首领战。',
    encounterType: 'boss',
    region: 'dungeon',
    risk: 'normal',
    spawnMultiplier: 2,
    recommendedLevel: 6,
    firstClearRewardGold: 420,
    nextNodeIds: ['n7'],
  },
  {
    id: 'n7',
    chapterId: 'chapter_volcano',
    order: 7,
    name: '焦灼熔道',
    description: '高伤怪群开场。',
    encounterType: 'normal',
    region: 'volcano',
    risk: 'normal',
    spawnMultiplier: 2,
    recommendedLevel: 7,
    firstClearRewardGold: 320,
    nextNodeIds: ['n8'],
  },
  {
    id: 'n8',
    chapterId: 'chapter_volcano',
    order: 8,
    name: '烈焰回廊',
    description: '高压怪群考验续航。',
    encounterType: 'wave',
    region: 'volcano',
    risk: 'nightmare',
    spawnMultiplier: 3,
    waveSize: 6,
    recommendedLevel: 8,
    firstClearRewardGold: 420,
    nextNodeIds: ['n9'],
  },
  {
    id: 'n9',
    chapterId: 'chapter_volcano',
    order: 9,
    name: '深渊火核',
    description: '终章首领，通关后可循环挑战。',
    encounterType: 'boss',
    region: 'volcano',
    risk: 'nightmare',
    spawnMultiplier: 3,
    recommendedLevel: 10,
    firstClearRewardGold: 680,
    nextNodeIds: ['n9'],
  },
];